app.swagger:
    path: /api/documentation.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
    path: /api/documentation
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
