parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_pgsql'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
        host: '%env(resolve:DATABASE_HOST)%'
        dbname: '%env(resolve:DATABASE_NAME)%'
        port: '%env(resolve:DATABASE_PORT)%'
        server_version: '10.5'
        types:
            uuid: App\Infrastructure\Persistence\Doctrine\Type\UuidType
    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            App:
                type: yml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/PostgreSQL/mapping'
                prefix: 'App\Domain\Entity'
